server:
  port: 8080

spring:
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /doc.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: default
      paths-to-match: /api/**

logging:
  level:
    cn.oa.mapper: debug
