server:
  port: 8080

logging:
  level:
    cn.oa: DEBUG

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oa_system_v2?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: oa_v2
    password: oa_v2
    driver-class-name: com.mysql.cj.jdbc.Driver
